services:
  altpoint:
    image: altpoint:1.0
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./src/AltPointClients/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__DB=Server=postgresdb;Port=5432;Database=altpoint;User Id=postgres;Password=passsupersafe;
    depends_on:
      - postgresdb
      - rabbitmq
  altpoint_consumer:
    image: altpoint_consumer:1.0
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./src/AltPoint.Api.Consumer/Dockerfile
    ports:
      - "5001:80"
    depends_on:
      - rabbitmq
  postgresdb:
    image: postgres
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - postgresdb-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: passsupersafe
      POSTGRES_USER: postgres
      POSTGRES_DB: altpoint
  rabbitmq:
    image: rabbitmq:3.10.7-management
    ports:
      - "15672:15672"
      - "5672:5672"
volumes:
  postgresdb-data: